# Generated by Django 3.1.7 on 2021-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=30)),
                ('taskdesc', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
